import { useAuth, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "~/components/Header";
import MainSection from "~/components/MainSection";
import SideBar from "~/components/SideBar";
import { ScrollArea } from "~/components/ui/scroll-area";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.spotify.playlists.useQuery({
    text: "from tRPC",
  });

  const { getToken } = useAuth();

  if (isLoading) return <div>Loading...</div>;

  // get user object

  console.log(getToken().then((token) => console.log(token)));

  return (
    <>
      <Head>
        <title>{data?.href}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen bg-black text-white">
        <SideBar />
        <MainSection />
      </div>
    </>
  );
};

export default Home;
("dsd");
