import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import MainSection from "~/components/MainSection";
import SideBar from "~/components/SideBar";
import { ScrollArea } from "~/components/ui/scroll-area";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen bg-black text-white">
        <SideBar />
        <MainSection />
      </div>
    </>
  );
};

export default Home;
("dsd");
